// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOr6d741Vjnecn8VuToaXvkIzY35vejUs',
    appId: '1:417943856854:web:878184193caf1f008c0b77',
    messagingSenderId: '417943856854',
    projectId: 'gmailfreelancing',
    authDomain: 'freelancing-e26a4.firebaseapp.com',
    storageBucket: 'gmailfreelancing.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXiNtHXPGaat6rkECWtveGl1HW2jxpTho',
    appId: '1:417943856854:android:44baaab00df02d6d8c0b77',
    messagingSenderId: '417943856854',
    projectId: 'gmailfreelancing',
    storageBucket: 'gmailfreelancing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-2pPAxryUF3EUcc1_ihKcWVOPowAWQL4',
    appId: '1:417943856854:ios:6fa0d5edae25e23f8c0b77',
    messagingSenderId: '417943856854',
    projectId: 'gmailfreelancing',
    storageBucket: 'gmailfreelancing.appspot.com',
    iosBundleId: 'com.example.freelancing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-2pPAxryUF3EUcc1_ihKcWVOPowAWQL4',
    appId: '1:417943856854:ios:398c41ad7c7641138c0b77',
    messagingSenderId: '417943856854',
    projectId: 'gmailfreelancing',
    storageBucket: 'gmailfreelancing.appspot.com',
    iosBundleId: 'com.example.freelancing.RunnerTests',
  );
}
